# Generated by Django 2.2.4 on 2019-09-26 11:59

import deeplearn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeplearn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deep',
            name='img',
            field=models.ImageField(null=True, upload_to='images\\', validators=[deeplearn.models.validate_img]),
        ),
    ]
